### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by detro** [nguyenduong/V8-iOS#1]
Hello,

I know how annoying can be when someone just comes along and says "do this! nau!".
But I think it would be super-valuable to know what this thing actually is and it's purpose.

We can guess from the name but... ;)

**Comment by nguyenduong** [comment]
Hi
My purpose is using V8 for my cross platform game engine. You can see at www.jacos2d-x.org:)

**Comment by detro** [comment]
OK. Sounds great.
But how are you going to bring it to iOS, where no language interpreters are allowed from App developers?

See, for example, Chrome for iOS: it's built using Apple's WebView and "standard" JavaScriptCore, as porting V8 was "not allowed".
